pygments: true
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027

permalink: /:categories/:year/:month/:day/:title 
safe: ture
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
lsi: false
source: api-design
destination: api-design
pygments: true

paginate: 10

title : API Aggregation