permalink: /:categories/:year/:month/:day/:title 
safe: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
lsi: false
source: api-evangelist
destination: api-evangelist
pygments: true

paginate: 10

title : API Integration

production_url : http://dev.apievangelist.com

BASE_PATH : http://dev.apievangelist.com

ASSET_PATH : false

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
