permalink: /:categories/:year/:month/:day/:title 
safe: ture
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
lsi: false
source: api-integration
destination: api-integration
pygments: true

paginate: 10

title : API Integration
tagline: 
author :
name : Kin Lane
email : info@apievangelist.com
github : kinlane
twitter : kinlane
feedburner : feedname

production_url : http://dev.apievangelist.com

BASE_PATH : http://dev.apievangelist.com

ASSET_PATH : false

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
